### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by Paul-g-g** [Tereshchenkolab/paper-ecg#8]
App fails to open (not responding). Running macOS Big Sur (11.5.2). Any ideas how to fix this issue? I would love to try out the application.
Thanks,

Paul

**Comment by julianfortune** [comment]
Hey Paul! I believe we just need to create a build for Big Sur (current build is for Catalina). I will create a new build and upload it when I get a chance!

(Note to self: Make a ticket to do builds automatically with MacOS / Ubuntu docker images)

**Comment by Paul-g-g** [comment]
Ah, I was wondering if that might be the case. Thanks for working on this — I’ll keep my eyes open for future updates.

**Comment by julianfortune** [comment]
Hey Paul,

I was hoping things were going to be easy, but that appears *not to be the case* (🤦🏼‍♀️). It looks like support for Big Sur isn't available for the version of Python we are using (3.6), and this version is required for the build system we are using to create the application. All of this is to say I have been unable to build a Big Sur application with the current code base.

1. I will look into building the app using Python 3.9 and `PyInstaller`.

2. In the meantime, you can try the application via "building" from source: 
    - Download the source code
    - Follow the instructions in [`SETUP.md`](https://github.com/Tereshchenkolab/paper-ecg/blob/master/SETUP.md)
    - Run 'fbs run' in the terminal

**Comment by gerardsimons** [comment]
I had the same problem and indeed managed to resolve this, by using the instructions above, but be aware that doing `pip install pyqt5` did not work for me since there is a license you need to agree, and it seems impossible to agree to it via pip (you can see it when you do `pip install --verbose`, otherwise it just seems stuck). If you use `brew install pyqt` and then the other requirements as is, it will work !

**Comment by tereshchenko9** [comment]
thank you for your interest and this comment that may help others. it depends on OS and admin rights.
